services:
  # Frontend service
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  # Backend service  
  backend:
    depends_on:
      - mongodb
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/mern-chat-app
      - GENERATIVE_API_KEY=AIzaSyA3V2G4SMUECgkoHn0Tfg87YTzlaZBWspw
      - EMAIL=writely41@gmail.com
      - PASSWORD=uhox dexo kmlp slhp
      - CLOUDINARY_ClOUD_NAME=ds1ceummz
      - CLOUDINARY_API_KEY=869577595372892
      - CLOUDINARY_API_SECRET=svN7OqOXtt8YadVOJ1XKbZ93MUw
      - JWT_SECRET=mern-chat-app-secret

  # MongoDB database
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: